name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install uv
        run: |
          make uv-download

      - name: Install dependencies
        run: |
          make venv
          uv pip install -e ."[dev]"
          uv run pre-commit install
        
      - name: Run style checks
        run: |
          make check-codestyle

      - name: Run docstrings checks
        run: |
          make docs

      - name: Run tests
        run: |
          make test
